spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_postgre
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: hello-pool
      maximum-pool-size: 20
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimitx: 2048
        useServerPrepStmts: true
      username: admin
      password: 123qwe

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
